### PR TITLE
code is now more beautifull

### PR DESCRIPTION
**Pull request by mauro-balades**

### CODE REVIEW

**Comment by omegaui** [comment]
Can you please explain what you did?
I am unable to figure it out.

**Comment by mauro-balades** [comment]
I just used this: https://github.com/jhipster/prettier-java
to make the code look more beautifull.

**Comment by mauro-balades** [comment]
let me remove the bin folder

**Comment by mauro-balades** [comment]
I have also added a .gitignore so that you don't need to delete the bin folder again and again. because git ignores it.

**Comment by omegaui** [comment]
also remove the contents of out folder except the stable and beta jar files and I will merge it

**Comment by omegaui** [comment]
Wait..
Don't do that
I just reviewed some files and I didn't liked the redefined code style.
(Everyone has a different taste)
Sorry!
But I cannot merge this pull request.
If you have any other features or change to propose then you are welcome.

Hope, you understand.

**Comment by mauro-balades** [comment]
ye

**Pull request closed without merging**
